[package]
name = "encript_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.98"
base64 = "0.22.1"
clap = {version = "4.5.41", features = ["derive"]}
rand = "0.9.2"
